require 'rails_helper'
require 'test_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.

RSpec.describe SystemAccessRequestsController, type: :controller do

    describe 'GET #external_action' do
system_access_request_exter=
nal_action?sar_id=3D15&amp;sar_action=3Dapproved&amp;authorization_code=3D=
67e300a7-efe3-43fc-af50-51c176f37665
        it 'returns sar not found' do
            get :external_action, sar_id: 123456, 
        end

        it 'returns auth code not found' do

        end

        it 'returns action is not allow' do

        end

        it 'returns auth code is already used' do

        end

        it 'returns sar is approved' do

        end

        it 'returns sar is rejected' do

        end    end
end
